### ISSUE TITLE
DefaultControllerSelector throws exception

### ISSUE THREAD

**Issue by TehWardy** [mono/aspnetwebstack#5]
No idea if its a bug in the controller selector code or if its the code I have around it as the app is quite complex.

I have asked this stack question:
http://stackoverflow.com/questions/32615769/owin-webapi-odata-v4-aspnet-identity-initialisation

The error in question:
```XML
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>
    ValueFactory attempted to access the Value property of this instance.
</ExceptionMessage>
<ExceptionType>System.InvalidOperationException</ExceptionType>
<StackTrace>
    at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value()
    at System.Web.Http.Dispatcher.DefaultHttpControllerSelector.GetControllerMapping()
    at Core.API.GenericControllerSelector.GetControllerMapping() in D:\clxtfs\Framework\Core.API\ODataControllerSelector.cs:line 93 
    at System.Web.Http.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, HttpConfiguration configuration, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider)
    at System.Web.Http.Routing.AttributeRoutingMapper.<>c__DisplayClass2.<>c__DisplayClass4.<MapAttributeRoutes>b__1() at System.Web.Http.Routing.RouteCollectionRoute.EnsureInitialized(Func`1 initializer)
    at System.Web.Http.Routing.AttributeRoutingMapper.<>c__DisplayClass2.<MapAttributeRoutes>b__0(HttpConfiguration config)
    at System.Web.Http.HttpConfiguration.ApplyControllerSettings(HttpControllerSettings settings, HttpConfiguration configuration)
    at System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type)
    at System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type)
    at System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type)
    at System.Web.Http.Controllers.HttpControllerDescriptor..ctor(HttpConfiguration configuration, String controllerName, Type controllerType)
    at System.Web.Http.Dispatcher.DefaultHttpControllerSelector.InitializeControllerInfoCache() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue()
    at System.Lazy`1.get_Value() at System.Web.Http.Dispatcher.DefaultHttpControllerSelector.SelectController(HttpRequestMessage request)
    at Core.API.GenericControllerSelector.SelectController(HttpRequestMessage request) in D:\clxtfs\Framework\Core.API\ODataControllerSelector.cs:line 39 
    at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
</StackTrace>
</Error>
```

I noticed there are some obvious situations like this:
http://forums.asp.net/t/2009235.aspx?Can+not+access+Web+API+service+with+OData4

... that doesn't appear to be my problem though ... is there some recommendation / best practice for getting WebAPI + OData + OWIN + Identity working?

I've seen loads on getting them individually working but I need a secure OData endpoint model that's extensible (I can add more odata contexts as I go).

**Comment by TehWardy** [comment]
Ok so I did a little work on this and built a custom odata controller selector that supports generics.
My version depends on some external stuff that OData doesn't have but might be a nice new addition to the framework ...

https://gist.github.com/TehWardy/3e505abd7e22d9e9930952104136963d

... this controller selector allowed me to create controllers like this ...

public class EntityODataController<T> : ODataController { ... }
public class DtoODataController<TDto, TEntity> : EntityODataController<TEntity> { ... }

... i then built a modelbuilder class that wraps up the OData calls a bit nicer for me in the same way that a dbcontext does in EF (or at least that was my aim) ...

 ```
public class ACOFIModelBuilder : ODataModelBuilder
    {
        public ACOFIModelBuilder() : base()
        {

        }

        public override ODataModel Build()
        {
            return new ODataModel
            {
                Context = "ACOFI",
                Description = "ACOFI Programme Management Data.",
                PathHandler = new DefaultODataPathHandler(),
                RoutingConventions = DefaultRoutingConventions,
                Model = BuildModel()
            };
        }

        IEdmModel BuildModel()
        {
               AddSet<T1>();
               AddSet<T2>();
        }
  }
```

Which then allows me to setup my app like this ...

https://gist.github.com/TehWardy/8780bf86f1c225f86d1d065db1582e91

... from my owin startup class I simply call configure.
